Capstone-Projects-2025-Spring/project-aac-game-team-a

documentation/docs/requirements/use-case-descriptions.md

Changed photo link in markdown file

---

documentation/docusaurus.config.js

Changing links and editing title

document updates

---

documentation/docs/api-specification/backendJSDoc.md
documentation/docs/api-specification/frontendJSDoc.md
documentation/docs/api-specification/openapi-spec.md

Fixed links to files in frontend, backend, swagger

Fixing ref links in api documentation

---

documentation/docs/system-architecture/design.md

These are my revisions to part 1 of the design document.

added necessary return arrows and explained diagram steps

---

documentation/docs/testing/integration-testing.md
test/integration.test.js

These are purely as a blueprint and will be revised as the project progresses

Add integration.test.js in test folder, and updated integration-testing.md

---

documentation/static/api-docs/swagger-ui-dist/swagger.yaml

This is going to update the swagger api doc

updating swagger

---

scribblersGame/src/router/index.ts
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue

Imported the "views" directory classes into the router for better router integration. 
Changed the element type from <button> to <RouterLink> in the Join and Host views

Fixed routing issue

---

scribblersGame/src/components/DrawingBoard.vue
scribblersGame/src/views/GameView.vue

Drawing board integration

---

gameFiles/backend/starter.cjs
gameFiles/frontend/drawing-canvas-aac/package-lock.json
gameFiles/frontend/drawing-canvas-aac/package.json
gameFiles/frontend/drawing-canvas-aac/src/App.vue
gameFiles/frontend/drawing-canvas-aac/src/main.js
scribblersServer/server.js

- Streaming canvas using websocket
- Converting image into base 64
- Need help integrating base64 into canvas for none drawers

Agta 92 display drawing board to users

---

scribblersGame/src/views/GameView.vue
scribblersServer/server.js

- first user to join becomes drawer
- a prompt is randomly selected and displayed
- other user can guess
- correct guess message shows up in chat
- correct guesses are hidden in the chat to other players
**turn taking isn't fully working. i can't get the you-are-drawer for the 2nd drawer to arrive. not sure why. ill continue later.***

Basic game flow - almost fully working (read desc)

---

scribblersGame/src/views/AvatarSelectView.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue

Removed the routing in between the Host/Join pages to the Avatar Selection page. Both pages now route to the game page. 
Added an avatar selection to the Host page

Adjusting page routing

---

scribblersGame/src/views/GameView.vue
scribblersServer/server.js

- drawing prompt banner is working
- switching roles after all guessed correctly is working
- drawer cant input guesses while drawing

Role switching

---

scribblersGame/src/views/GameView.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue
scribblersServer/server.js

Users now enter rooms based on the codes entered in the host and join screens. These two screens could be redundant unless gameflow is altered.
Guesses from the AAC board, drawing data, and timer data are sent to everyone in the same room. Other game state information will need to be implemented in the future.

Implement backend rooms

---

scribblersGame/src/views/GameView.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue

Added back buttons for Host and Join views.
Added quit button for Game view.

Added back buttons

---

scribblersGame/src/views/GameView.vue
scribblersServer/server.js

Chat messages are no longer added to chat
A message board displays user avatars
The text for the users is updated rather than treated as another message

Message board update

---

gameFiles/frontend/drawing-canvas-aac/src/main.js
scribblersGame/package-lock.json
scribblersGame/src/components/DrawingBoard.vue
scribblersGame/src/components/aacBoard.vue
scribblersGame/src/views/GameView.vue

Accessability update

---

scribblersGame/src/components/HomeViewContent.vue

Nerfed main title

---

scribblersGame/src/views/GameView.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue

Reverts Capstone-Projects-2025-Spring/project-aac-game-team-a#80

Revert "added room code digit and added room code display in-game"

---

.github/workflows/fly-deploy.yml
scribblersGame/.dockerignore
scribblersGame/Dockerfile
scribblersGame/fly.toml
scribblersGame/package-lock.json
scribblersGame/src/views/GameView.vue
scribblersServer/.dockerignore
scribblersServer/Dockerfile
scribblersServer/fly.toml

Application is now publicly reachable at the following link: [https://scribblersgame.fly.dev](https://scribblersgame.fly.dev)

Scribblers Public

---

scribblersGame/src/components/DrawingBoard.vue
scribblersGame/src/views/GameView.vue
scribblersServer/server.js

Added the following:
Drawer is the only player who can see drawing tools (colors, width, clear, undo)
Drawer is the only player who can draw during their turn
Canvas is automatically cleared after each round

Drawing Canvas Logic

---

scribblersGame/src/components/WaitingRoom.vue
scribblersGame/src/objects/SocketClientHandler.js
scribblersGame/src/stores/GameState.ts
scribblersGame/src/views/GameView.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue
scribblersServer/server.js

Removed some redundant code and created an object for client socket listeners, had issues with getting listeners to properly update values but can revisit moving these listeners to this object in the future

Code clean

---

scribblersGame/src/components/HomeViewContent.vue
scribblersGame/src/components/WaitingRoom.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue

Refactored the speakNow function in each class
Added TTS for waiting room

WaitingRoom TTS

---

scribblersGame/src/components/DrawingBoard.vue
scribblersGame/src/components/aacBoard.vue
scribblersGame/src/views/GameView.vue

Added TTS for drawing board tools and AAC board buttons

Tts for game

---

scribblersGame/index.html
scribblersGame/src/components/HomeViewContent.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue

Added UserWay script 
Changed the size of the settings button

More accesibility

---

scribblersGame/src/views/GameView.vue

after user guesses correctly the aac board is hidden until next round.

hide aac board

---

scribblersGame/src/components/aacBoard.vue
scribblersGame/src/views/GameView.vue

Buttons for AAC guess board will stay contained
the board stays a consistent to compensate for button overflow

AAC Guess board restyling

---

scribblersGame/src/views/GameView.vue
scribblersGame/src/views/HostLobbyView.vue
scribblersGame/src/views/JoinLobbyView.vue
scribblersServer/server.js

- Prevent users from joining game if they do not pass the following checks:
1. Their Avatar is not already chosen
2. The max number of players has not been reached 
3. The requested lobby exists

Join Room Verification

---

scribblersGame/src/components/GuessBoard.vue
scribblersGame/src/components/aacBoard.vue
scribblersGame/src/views/GameView.vue

Fixed deployment error with currentGuess not being properly referenced. Removed score until scoring is added.

Fixed deployment

---

scribblersGame/src/views/GameView.vue
scribblersServer/objects/SocketServerHandler.js

when a guess is checked in the backend, we check if everyone has guessed correctly, and we send a websocket message to all frontends telling them that everyone guessed correctly. Then we call a function that triggers a 4 second popup as the round switches.

added popup message when all users guess correct

---

scribblersGame/src/components/EndGameScreen.vue
scribblersGame/src/components/WaitingRoom.vue
scribblersGame/src/views/GameView.vue
scribblersServer/objects/SocketServerHandler.js

Leaderboard is shown
Play again button (for host)
Leave lobby button

Agta 149 end of game screen

---

scribblersGame/src/components/GuessBoard.vue
scribblersServer/objects/GameData.js

Changed CSS styling for board
Guesses now reset on turn end

Guess board revamp

---

scribblersGame/src/views/GameView.vue

added guess indicator when you are guessing. it's a box in the top that says guess the drawing. it speaks it also when you click.

Guess indicator

---

scribblersGame/src/components/DrawingBoard.vue

fixed the coordinate calculation

Fixed coordinates for touchscreen/mouse

---

scribblersGame/src/components/GuessBoard.vue
scribblersGame/src/objects/SocketClientHandler.js

There was a bug (ahem Terrells fault) with the drawer being displayed to the message board

Drawer is now displayed in message board

---

documentation/docs/system-architecture/design.md
documentation/docs/system-architecture/development-environment.md
gameFiles/frontend/drawing-canvas-aac/src/style.css
scribblersGame/src/components/DrawingBoard.vue
scribblersGame/src/components/HomeViewContent.vue

Added main menu music and fixed undo button bugs

Menu theme

---

scribblersGame/src/components/GuessBoard.vue
scribblersGame/src/views/JoinLobbyView.vue

Fixed roomcode 'clear' function

---

scribblersGame/src/components/HomeViewContent.vue

Changed when music plays

---

docker-compose.yaml
scribblersGame/Dockerfile
scribblersGame/src/views/GameView.vue

To execute the program locally:
- Verify docker installation in command prompt with `docker version` command. [Install Docker](https://docs.docker.com/desktop/setup/install/windows-install/) if not already installed.
- Run `docker compose up -d` in the project root to build the project stack
- Connect locally in web browser with localhost, or connect from another device on the same network by entering host device's IP (no ports!) into another device's web browser.

Docker compose file added
